=== githubzoujiayun/AndroidRepo/UiAutomatorTest/test-res/jobtest.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	elementFormDefault="qualified" attributeFormDefault="qualified">

	<!-- enumeration type -->
	<xsd:simpleType name="conditionEnum">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="view_exist" />
			<xsd:enumeration value="view_not_exist"/>
			<!-- <xsd:enumeration value="text_equals"/> -->
			<!-- <xsd:enumeration value="text_matches"/> -->
		</xsd:restriction>
	</xsd:simpleType>
	
	<xsd:simpleType name="scrollEnum">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="none" />
			<xsd:enumeration value="vertical" />
			<xsd:enumeration value="horizontal" />
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:simpleType name="swipeEnum">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="none" />
			<xsd:enumeration value="left" />
			<xsd:enumeration value="right" />
			<xsd:enumeration value="up" />
			<xsd:enumeration value="down" />
			<xsd:enumeration value="r2l" />
			<xsd:enumeration value="l2r" />
			<xsd:enumeration value="d2u" />
			<xsd:enumeration value="u2d" />
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:simpleType name="waitEnum">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="wait_for_exist" />
			<xsd:enumeration value="wait_until_gone" />
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:simpleType name="pressKeyEnum">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="search" />
			<xsd:enumeration value="back" />
			<xsd:enumeration value="home" />
			<xsd:enumeration value="menu" />
			<xsd:enumeration value="enter" />
			<xsd:enumeration value="delete" />
			<xsd:enumeration value="keycode" />

		</xsd:restriction>
	</xsd:simpleType>

	<xsd:simpleType name="indexType">
		<xsd:restriction base="normalizedString">
			<xsd:pattern value="([0-9]+:)*[0-9]+" />
		</xsd:restriction>
	</xsd:simpleType>

	<!-- general attributes,all nodes has these attributes -->
	<xsd:attribute name="id" type="xsd:string"></xsd:attribute>
	<xsd:attribute name="condition" type="conditionEnum"></xsd:attribute>
	<xsd:attribute name="conditionNodeId" type="xsd:string"></xsd:attribute>
	<xsd:attribute name="enabled" type="xsd:boolean"></xsd:attribute>
	<xsd:attribute name="resId" type="xsd:string"></xsd:attribute>
	<xsd:attribute name="resIdMatches" type="xsd:string"></xsd:attribute>
	<xsd:attribute name="clickable" type="xsd:boolean"></xsd:attribute>
	<xsd:attribute name="description" type="xsd:string"></xsd:attribute>
	<xsd:attribute name="scrollable" type="scrollEnum"></xsd:attribute>
	<xsd:attribute name="swipeDirection" type="xsd:string"></xsd:attribute>
	<xsd:attribute name="timeout" type="xsd:positiveInteger"></xsd:attribute>
	<xsd:attribute name="typed" type="xsd:string"></xsd:attribute>
	<xsd:attribute name="componentName" type="xsd:string"></xsd:attribute>

	<!-- attributes only for jobcase -->
	<xsd:attribute name="className" type="xsd:string"></xsd:attribute>
	<xsd:attribute name="resultType" type="xsd:string"></xsd:attribute>

	<!-- attribute only for click -->

	<!-- attribute only for text -->
	<xsd:attribute name="text" type="xsd:string"></xsd:attribute>
	<xsd:attribute name="textMatches" type="xsd:string"></xsd:attribute>
	<xsd:attribute name="textContains" type="xsd:string"></xsd:attribute>
	<xsd:attribute name="textStartsWith" type="xsd:string"></xsd:attribute>

	<!-- attribute only for input -->

	<!-- attribute only for record -->

	<!-- attribute only for indexView -->
	<xsd:attribute name="indexs" type="indexType"></xsd:attribute>
	<xsd:attribute name="rootClass" type="xsd:string"></xsd:attribute>
	<xsd:attribute name="rootIndex" type="xsd:positiveInteger"></xsd:attribute>
	<xsd:attribute name="rootResId" type="xsd:string"></xsd:attribute>

	<!-- attribute only for wait -->
	<xsd:attribute name="waitType" type="waitEnum"></xsd:attribute>

	<!-- attribute only for press -->
	<xsd:attribute name="pressKey" type="pressKeyEnum" use="required"></xsd:attribute>
	<xsd:attribute name="keyCode" type="xsd:string"></xsd:attribute>
	<xsd:attribute name="metaState" type="xsd:string"></xsd:attribute>

	<!-- attribute only for swipe -->
	<xsd:attribute name="swipeCount" type="xsd:string"></xsd:attribute>

	<xsd:attributeGroup name="generalAttributes">
		<xsd:attribute ref="id" />
		<xsd:attribute ref="condition" />
		<xsd:attribute ref="conditionNodeId" />
		<xsd:attribute ref="enabled" />
		<xsd:attribute ref="resId" />
		<xsd:attribute ref="resIdMatches" />
		<xsd:attribute ref="clickable" />
		<xsd:attribute ref="description" />
		<xsd:attribute ref="scrollable" />
		<xsd:attribute ref="swipeDirection" />
		<xsd:attribute ref="timeout" />
		<xsd:attribute ref="typed" />
		<xsd:attribute ref="componentName" />
	</xsd:attributeGroup>

	<xsd:attributeGroup name="jobcaseAttributes">
		<xsd:attributeGroup ref="generalAttributes" />
		<xsd:attribute ref="className" />
		<xsd:attribute ref="resultType" />
	</xsd:attributeGroup>

	<xsd:attributeGroup name="clickAttributes">
		<xsd:attributeGroup ref="generalAttributes" />
	</xsd:attributeGroup>

	<xsd:attributeGroup name="textAttributes">
		<xsd:attributeGroup ref="generalAttributes" />
		<xsd:attribute ref="text" />
		<xsd:attribute ref="textMatches" />
		<xsd:attribute ref="textContains" />
		<xsd:attribute ref="textStartsWith" />
	</xsd:attributeGroup>

	<xsd:attributeGroup name="inputAttributes">
		<xsd:attributeGroup ref="generalAttributes" />
	</xsd:attributeGroup>

	<xsd:attributeGroup name="recordAttributes">
		<xsd:attributeGroup ref="generalAttributes" />
	</xsd:attributeGroup>

	<xsd:attributeGroup name="indexAttributes">
		<xsd:attributeGroup ref="generalAttributes" />
		<xsd:attribute ref="indexs" />
		<xsd:attribute ref="rootClass" />
		<xsd:attribute ref="rootIndex" />
		<xsd:attribute ref="rootResId" />
	</xsd:attributeGroup>

	<xsd:attributeGroup name="waitAttributes">
		<xsd:attributeGroup ref="generalAttributes" />
		<xsd:attribute ref="waitType" />
	</xsd:attributeGroup>

	<xsd:attributeGroup name="pressAttributes">
		<xsd:attributeGroup ref="generalAttributes" />
		<xsd:attribute ref="pressKey" />
		<xsd:attribute ref="keyCode" />
		<xsd:attribute ref="metaState" />
	</xsd:attributeGroup>

	<xsd:attributeGroup name="swipeAttributes">
		<xsd:attributeGroup ref="generalAttributes" />
		<xsd:attribute ref="swipeCount" />
	</xsd:attributeGroup>


	<!-- events -->

	<xsd:group name="eventChoice">
		<xsd:choice>
			<xsd:element ref="click" />
			<xsd:element ref="input" />
			<xsd:element ref="wait" />
			<xsd:element ref="press" />
			<xsd:element ref="swipe" />
			<xsd:element ref="record" />
		</xsd:choice>
	</xsd:group>

	<xsd:element name="text">
		<xsd:complexType mixed="true">
			<xsd:attributeGroup ref="textAttributes" />
		</xsd:complexType>
	</xsd:element>
	
	<xsd:element name="indexView">
		<xsd:complexType>
			<xsd:attributeGroup ref="indexAttributes" />
		</xsd:complexType>
	</xsd:element>

	<xsd:group name="viewChoice">
		<xsd:choice>
			<xsd:element ref="text" />
			<xsd:element ref="indexView" />
		</xsd:choice>
	</xsd:group>

	<xsd:group name="nodeChoice">
		<xsd:choice>
			<xsd:group ref="viewChoice" />
			<xsd:group ref="eventChoice" />
		</xsd:choice>
	</xsd:group>
	

	<xsd:element name="click">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:group ref="nodeChoice" minOccurs="1" maxOccurs="unbounded" />
			</xsd:sequence>
			<xsd:attributeGroup ref="clickAttributes" />
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="input">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:group ref="nodeChoice" minOccurs="1" maxOccurs="unbounded" />
			</xsd:sequence>
			<xsd:attributeGroup ref="inputAttributes" />
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="wait">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:group ref="viewChoice" minOccurs="1" maxOccurs="unbounded" />
			</xsd:sequence>
			<xsd:attributeGroup ref="waitAttributes" />
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="press">
		<xsd:complexType>
			<xsd:attributeGroup ref="pressAttributes" />
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="swipe">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:group ref="nodeChoice" minOccurs="1" maxOccurs="unbounded" />
			</xsd:sequence>
			<xsd:attributeGroup ref="swipeAttributes" />
		</xsd:complexType>
	</xsd:element>
	
	<xsd:element name="record">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:group ref="viewChoice" minOccurs="1" maxOccurs="unbounded" />
			</xsd:sequence>
			<xsd:attributeGroup ref="recordAttributes" />
		</xsd:complexType>
	</xsd:element>
	
	<xsd:element name="record">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:group ref="viewChoice" minOccurs="1" maxOccurs="unbounded" />
			</xsd:sequence>
			<xsd:attributeGroup ref="recordAttributes" />
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="jobcase">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:group ref="eventChoice" maxOccurs="unbounded" />
			</xsd:sequence>
			<xsd:attributeGroup ref="jobcaseAttributes" />
		</xsd:complexType>
	</xsd:element>
</xsd:schema>

=== githubzoujiayun/AndroidRepo/testAndroid/codes/JobTest/test-res/backup/test1.xml
<?xml version="1.0" encoding="utf-8"?>

<jobcase 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="jobtest.xsd"
    enabled="false">
    <click>
	    <text>"校园招聘"</text>
        <text>"科系搜索"</text>
        <text>"医学"</text>
    </click>
    <wait
        type="wait_until_gone"
        timeout="20000"
        >
        <text
            textMatches="数据加载中。*"
            />
    </wait>
    <click>
        <text resId="com.job.android:id/rightImageButton"/>
        <text>"医学类"</text>
        <text>"培训"</text>
    </click>
    <wait
        type="wait_until_gone"
        timeout="20000"
        >
       <text
            textMatches="数据加载中。*"
            />
    </wait>
    <click>
        <indexView
			rootClass="android.widget.ListView"
			rootIndex="0"
			indexs="2:0"
            >
        </indexView>
    </click>
    <record condition="view_exist">
        <text
            scrollable="VERTICAL"
            text="举报职位"
		/>
    </record>
</jobcase>

=== githubzoujiayun/AndroidRepo/UiAutomatorTest/test-res/backup/1.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<jobcase
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="jobtest.xsd"
    enabled="false"
    >
    <click>

        <indexView
            indexs="5"
            resId="com.job.android:id/home_page_gridview"
            rootClass="android.widget.GridView" />
    </click>

    <swipe>

        <text
            resId="com.job.android:id/content_layout"
            swipeDirection="left" />
    </swipe>

    <click>

        <text resId="com.job.android:id/goback" />
    </click>

    <click>

        <indexView
            indexs="5"
            resId="com.job.android:id/home_page_gridview"
            rootClass="android.widget.GridView" />
    </click>

    <swipe>

        <text
            resId="com.job.android:id/flipView"
            swipeDirection="left" />
    </swipe>

    <swipe>

        <text
            resId="com.job.android:id/flipView"
            swipeDirection="left" />
    </swipe>

    <click>

        <indexView
            indexs="4"
            resId="com.job.android:id/resume_home_gridview"
            rootClass="android.widget.GridView" />
    </click>

    <click>

        <indexView
            indexs="2"
            rootClass="android.widget.ListView"
            rootResId="com.job.android:id/dlv_operation_select" />
    </click>

    <click>

        <text resId="com.job.android:id/content_layout" />
    </click>

    <click> <!-- unknown attrribute : MonkeyTalkEvent [mComponent=Scroller, mMonkeyID=#4, mAction=tap, mArgument=null, mTimeout=0, mThinkTime=0, mShouldFailed=false] -->

        <text unknown="#4" />
    </click>

    <click>
        <text text="修改名称" />
    </click>

    <input>

        <text
            text="请输入简历名称"
            typed="ummaryffd" />
    </input>

    <swipe>

        <text
            swipeDirection="right"
            text="保存" />
    </swipe>

    <click>

        <text resId="com.job.android:id/goback" />
    </click>

</jobcase>

=== githubzoujiayun/AndroidRepo/testAndroid/codes/JobTest/test-res/backup/test3.xml
<?xml version="1.0" encoding="utf-8"?>
<jobcase xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="jobtest.xsd" enabled="false">
	<click>
		<text>"简历中心"</text>
	</click>
	<wait waitType="wait_until_gone">
		<text textMatches="数据加载中.*" />
	</wait>
	<swipe swipeCount="2">
		<text resId="com.job.android:id/content_layout" swipeDirection="left" />
	</swipe>
	<click>
		<text>"设置公开程度"</text>
		<text>"对所有公开"</text>
	</click>
	<click condition="view_exist">
		<text>"确定"</text>
	</click>
	<click>
		<text>"刷新简历"</text>
	</click>
</jobcase>

=== githubzoujiayun/AndroidRepo/UiAutomatorTest/test-res/backup/test5.xml
<?xml version="1.0" encoding="utf-8"?>
<jobcase
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="jobtest.xsd"
    >
    <click>
        <text>"简历中心"</text>
    </click>
    <wait waitType="wait_until_gone">
        <text textMatches="数据加载中.*"></text>
    </wait>
    <click>
        <text>"设置公开程度"</text>
        <text>"完全保密"</text>
        <text>"编辑简历"</text>
        <text>"修改名称"</text>
    </click>
    <input>
        <text resId="com.job.android:id/resume_rename_edit"
            typed="	Hello World!"></text>
    </input>
    <click>
        <text>"保存"</text>
        <text resId="com.job.android:id/goback"></text>
    </click>
    <record>
        <text resId="com.job.android:id/resume_home_openstatus"></text>
    </record>
</jobcase>

=== githubzoujiayun/AndroidRepo/testAndroid/codes/JobTest/test-res/backup/test2.xml
<?xml version="1.0" encoding="utf-8"?>
<jobcase
 	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="jobtest.xsd"
    enabled="false"
    >
    <click>
    	<text>"登录"</text>
    	<text>"注册"</text>        
    	<text>"手机号注册"</text>
    </click>
    <input>
        <text
            typed="#"
            text="请输入手机号"
            />
        <text
            typed="121212"
            text="请输入验证码"
            />
    </input>
    <click>
        <text>"获取验证码"</text>
    </click>
    <record condition="view_not_exist">
        <text>"uuid为空"</text>
    </record>
</jobcase>
